github: alxndr-w
ko_fi: alxndr-w
# Auch @tyrant88 hat sich danach zu richten, Änderungen als PR einzureichen und wie in den FriendsOfREDAXO-Regeln beschrieben sich vorbildhaft zu verhalten, statt heimlich in anderen Repos irgendwelche Änderungen zu committen. 😘?
