package: neues
version: '3.3.0'
author: 'Alexander Walther'
supportpage: https://alexplusde.github.io/neues/
load: late

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.12
    packages:
        yform: '^4,<5'
        yform_field: '^2.3.0'


page:
    title: translate:neues
    prio: 100
    icon: rex-icon fa-gear

pages:
    neues:
        title: translate:neues
        main: true
        block: system
        prio: 16
        icon: rex-icon fa-bullhorn
        perm: neues[]
        subpages: 
            entry:
                title: translate:neues_entry
                icon: rex-icon fa-bullhorn
                perm: neues[date]
            category:
                title: translate:neues_category
                icon: rex-icon fa-folder
                perm: neues[category]
            author:
                title: translate:neues_author
                icon: rex-icon fa-user
                perm: neues[author]
            lang:
                title: translate:neues_lang
                perm: neues[lang]
                icon: rex-icon fa-flag
            settings:
                title: translate:neues_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:neues_help
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: neues[docs]

default_config:
    default_author: "Redaktion"
    default_thumbnail: ""
    external_url_label: "Zur Website"
    editor: 'class="form-control redactor-editor--default"'
