package: neues
version: '2.1.0-beta'
author: 'Alexander Walther'
supportpage: https://alexplusde.github.io/neues/
load: late

requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.12
    packages:
        yform: '^4,<5'


page:
    title: translate:neues
    prio: 100
    icon: rex-icon fa-gear

pages:
    neues:
        title: translate:neues
        main: true
        block: system
        prio: 16
        icon: rex-icon fa-bullhorn
        perm: neues[]
        subpages: 
            date:
                title: translate:neues_entry
                icon: rex-icon fa-bullhorn
                subPath: pages/data_edit.php
                yformTable: rex_neues_entry
                yformClass: rex_neues_entry
                yformTitle: false
                perm: neues[date]
            category:
                title: translate:neues_category
                icon: rex-icon fa-folder
                subPath: pages/data_edit.php
                yformTable: rex_neues_category
                yformClass: rex_neues_category
                yformTitle: false
                perm: neues[category]
            date_lang:
                title: translate:neues_lang
                perm: neues[date_lang]
                icon: rex-icon fa-flag
                subPath: pages/data_edit.php
                yformTable: rex_neues_entry_lang
                yformClass: rex_neues_entry_lang
                yformTitle: false
            settings:
                title: translate:neues_settings
                icon: rex-icon fa-gear
                itemclass: pull-right
                perm: admin
            docs:
                title: translate:neues_help
                subPath: README.md
                icon: rex-icon fa-info-circle
                itemclass: pull-right
                perm: neues[docs]

default_config:
    neues_default_author: "Redaktion"
    neues_default_thumbnail: ""
    neues_default_url_label: "Zur Website"
