package: neues
version: '7.0.0-dev'
author: Friends of REDAXO
supportpage: https://github.com/FriendsofREDAXO/neues

requires:
    php:
        version: '>8.2,<9'
    redaxo: '^5.18.3'
    packages:
        yform: '>4.1.1,<6'

page:
    title: translate:neues
    prio: 100
    icon: rex-icon fa-gear
    app_type: app # wird von @alxndr-w benötigt
    app_scope: user # wird von @alxndr-w benötigt

pages:
    neues:
        title: translate:neues
        main: true
        block: system
        prio: 16
        icon: rex-icon fa-bullhorn
        perm: neues[]
        subpages:
            entry:
                title: translate:neues_entry
                icon: rex-icon fa-bullhorn
                perm: neues[date]
                subPath: pages\yform.php
            category:
                title: translate:neues_category
                icon: rex-icon fa-folder
                perm: neues[category]
                subPath: pages\yform.php
            author:
                title: translate:neues_author
                icon: rex-icon fa-user
                perm: neues[author]
                subPath: pages\yform.php
            lang:
                title: translate:neues_lang
                perm: neues[lang]
                icon: rex-icon fa-flag
                subPath: pages\yform.php
            settings:
                title: translate:neues_settings
                icon: rex-icon fa-gear
                itemClass: pull-right
                perm: admin
            docs:
                title: translate:neues_help
                icon: rex-icon fa-info-circle
                itemClass: pull-right
                perm: neues[docs]

yform:
    neues/entry:
        table_name: FriendsOfRedaxo\Neues\Entry
    neues/category:
        table_name: FriendsOfRedaxo\Neues\Category
    neues/author:
        table_name: FriendsOfRedaxo\Neues\Author
    neues/lang:
        table_name: FriendsOfRedaxo\Neues\EntryLang

default_config:
    default_author: "Redaktion"
    default_thumbnail: "neues_entry_fallback_image.png"
    external_url_label: "Zur Website"
    editor: 'class="form-control redactor-editor--default"'
    url_profile: false
    schema_type: "Article"
